// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb9HuNUkf5YH-oy0DcrgtgPg61piDcNq0',
    appId: '1:40837142613:web:1543e893d8db950e0f1cdc',
    messagingSenderId: '40837142613',
    projectId: 'studybrahmastra-1874b',
    authDomain: 'studybrahmastra-1874b.firebaseapp.com',
    storageBucket: 'studybrahmastra-1874b.firebasestorage.app',
    measurementId: 'G-GPB0Q53C3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7WdaThN8opE8ZXeCl6_VFXWWjk8xyoM0',
    appId: '1:40837142613:android:517bdd0c5aa42a490f1cdc',
    messagingSenderId: '40837142613',
    projectId: 'studybrahmastra-1874b',
    storageBucket: 'studybrahmastra-1874b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiTq6koovdvIAdA8BtYgFkJcItPeCZYzE',
    appId: '1:40837142613:ios:c571bd5dfef204fd0f1cdc',
    messagingSenderId: '40837142613',
    projectId: 'studybrahmastra-1874b',
    storageBucket: 'studybrahmastra-1874b.firebasestorage.app',
    iosBundleId: 'com.example.studyBrahmastra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiTq6koovdvIAdA8BtYgFkJcItPeCZYzE',
    appId: '1:40837142613:ios:c571bd5dfef204fd0f1cdc',
    messagingSenderId: '40837142613',
    projectId: 'studybrahmastra-1874b',
    storageBucket: 'studybrahmastra-1874b.firebasestorage.app',
    iosBundleId: 'com.example.studyBrahmastra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb9HuNUkf5YH-oy0DcrgtgPg61piDcNq0',
    appId: '1:40837142613:web:2cb82a016d12e1db0f1cdc',
    messagingSenderId: '40837142613',
    projectId: 'studybrahmastra-1874b',
    authDomain: 'studybrahmastra-1874b.firebaseapp.com',
    storageBucket: 'studybrahmastra-1874b.firebasestorage.app',
    measurementId: 'G-PC4Y7PXFZ7',
  );
}
